name            : example
description     : Example project for image_sequence_animator.
version         : 2.0.0
author          : Ali Yigit Bireroglu <aliyigitbireroglu@gmail.com>
repository      : https://github.com/aliyigitbireroglu/flutter-image-sequence-animator
homepage        : https://www.cosmossoftware.coffee

environment     :
  sdk: '>=2.12.0 <3.0.0'

dependencies    :
  flutter                :
    sdk: flutter
  image_sequence_animator:
    path: ../
  spring_button          : ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter         :
  uses-material-design: true

  assets              :
    - assets/ImageSequence/
